name: Nostr action
description: Send EVENT to Nostr
branding:
  icon: message-circle
  color: purple
inputs:
  relays:
    description: Relay URLs `wss://...` (separated by `\n`)
    required: true
  private-key:
    description: Private key (nsec or hex)
    required: true
  content:
    description: Content
    required: false
    default: ''
  kind:
    description: Kind
    required: false
    default: '1'
  tags:
    description: Tags
    required: false
    default: '[]'
outputs:
  event:
    description: Published event
runs:
  using: node16
  main: dist/index.js
