name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: npm run prepare
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - uses: snow-actions/git-config-user@v1.0.0
      - name: Commit & Push
        run: |
          set -x
          git add .
          git commit -m 'npm run prepare'
          git push
        if: steps.diff.outcome == 'failure'
