name: Released

on:
  release:
    types: [ released ]

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@v1.8.1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            Release ${{ github.repository }} ${{ github.event.release.name }}
            ${{ github.event.release.html_url }}
          tags: |
            - ["proxy", "${{ github.event.release.html_url }}", "web"]
  user-status:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "expiration=$(date +%s --date '12 hours')" >> $GITHUB_ENV
      - uses: snow-actions/nostr@v1.8.1
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          kind: 30315
          content: |
            Release ${{ github.repository }} ${{ github.event.release.name }}
          tags: |
            - ["d", "general"]
            - ["r", "${{ github.event.release.html_url }}"]
            - ["expiration", "${{ env.expiration }}"]
