name: Released

on:
  release:
    types: [ released ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: snow-actions/nostr@v1.5.0
        with:
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
          content: |
            Release ${{ github.repository }} ${{ github.event.release.name }}
            ${{ github.event.release.html_url }}
