name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
        env:
          NOSTR_RELAYS: ${{ vars.NOSTR_RELAYS_TEST }}
          NOSTR_PRIVATE_KEY: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: |
          npm ci
          npm run package

      - name: Default is kind 1
        uses: ./
        with:
          relays: ${{ vars.NOSTR_RELAYS_TEST }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
          content: |
            test
            https://github.com/snow-actions/nostr
        id: publish
      - run: test $(echo "$event" | jq '.kind') = 1
        env:
          event: ${{ steps.publish.outputs.event }}
      - run: test "$event" != ''
        env:
          event: ${{ steps.publish.outputs.event }}

      - name: Reply with tags
        uses: ./
        with:
          relays: ${{ vars.NOSTR_RELAYS_TEST }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
          content: test reply
          tags: |
            - ["e", "${{ fromJson(steps.publish.outputs.event).id }}", "", "root"]
            - ["p", "${{ fromJson(steps.publish.outputs.event).pubkey }}"]
        id: publish-reply
      - run: test "$event" != ''
        env:
          event: ${{ steps.publish-reply.outputs.event }}

      - name: Specify kind
        uses: ./
        with:
          relays: ${{ vars.NOSTR_RELAYS_TEST }}
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
          content: wss://relay.nostr.wirednet.jp
          kind: 2
        id: publish-kind
      - run: test $(echo "$event" | jq '.kind') = 2
        env:
          event: ${{ steps.publish-kind.outputs.event }}
