name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
        env:
          NOSTR_RELAYS: ${{ vars.NOSTR_RELAYS_TEST }}
          NOSTR_PRIVATE_KEY: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    # kind 1 (default)
    - uses: ./
      with:
        relays: ${{ vars.NOSTR_RELAYS_TEST }}
        private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
        content: |
          test
          https://github.com/snow-actions/nostr
      id: publish
    - run: test "$event" != ''
      env:
        event: ${{ steps.publish.outputs.event }}

    # kind 2
    - uses: ./
      with:
        relays: ${{ vars.NOSTR_RELAYS_TEST }}
        private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
        content: wss://relay.nostr.wirednet.jp
      id: publish-2
    - run: test "$event" != ''
      env:
        event: ${{ steps.publish-2.outputs.event }}
